#!/bin/bash
ab -n 100 -c 5 http://127.0.0.1:8088/ > test_result_aiohttp.txt
ab -n 100 -c 10 http://127.0.0.1:8088/ >> test_result_aiohttp.txt
ab -n 100 -c 20 http://127.0.0.1:8088/ >> test_result_aiohttp.txt
ab -n 100 -c 40 http://127.0.0.1:8088/ >> test_result_aiohttp.txt
